highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Emma Winston's CV
name: Emma Winston
email: email
email_full: mailto:emma.winston@gmail.com
website: web
website_full: https://emmawinston.me
github: emmawinston
twitter: deer_ful
academia: https://goldsmiths.academia.edu/EmmaWinston
linkedin: https://www.linkedin.com/in/emma-winston-a6964758
soundcloud: http://soundcloud.com/deerful
music: https://deerful.com/
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/Goldsmiths+University+of+London/@51.4736202,-0.0395374,17z/data=!3m1!4b1!4m2!3m1!1s0x487602f81f1bd2cf:0xeb2cff5d2300d7f8'
address: Goldsmiths College
postcode: SE14 6NW
city: London
country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
